### ISSUE TITLE
Create new 0.4.0 release in Github

### ISSUE THREAD

**Issue by klinga** [BookOps-CAT/bookops-bpl-solr#13]
Since required Python moved up to 3.8, let's create a new release. This can be relevant for pip installing this package.
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

We should consider in the near future automating this in a PR/CI

**Comment by charlottekostelic** [comment]
New release (0.4.0) published with changes from PRs #12, #16, #17, #18, #19, and #20.
